### ISSUE TITLE
React & Redux Group Project: Setting Up the Kanban Board

### ISSUE THREAD

**Issue by rmiyoyo** [rmiyoyo/space-travelers-hub#25]
# Work Done
We created a Kanban board with a GitHub project.

# Group Members(3)
1. [Raphael Miyoyo](@rmiyoyo)
2. [Samuel Takyi Boateng](@SamuelTakyiBoateng)
3. [Richard Sikaonga](@richie1988)

# Project
[Link to Project](https://github.com/rmiyoyo/space-travelers-hub/projects/1)

**Comment by nedjwab** [comment]
# 🟢 Project Approved! 🏆

## Hi  @luigirazum                    👋

Your project is complete! ✔️✔  🏁

## Highlights 🌟

- ✔️ Your kanban board is ready  🎇

Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.


_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
